/* Слова для устного английского (Шкода Ю.Д.) — Unit 1 Entertainment, Unit 2 Sightseeing.
   Один источник данных: его читают и words.html, и окно прогресса в app.js.
   Формат слова: [слово, значение по-английски, перевод]. Слово = уникальный id (не повторять между группами).
   Группы Unit 2 имеют id с префиксом v2 — по нему words.html относит их к категории «Vocabulary U.2». */
window.EN_WORDS = [
  { id: 'u1a', title: 'p.8–9 · Привычки (Habits)', words: [
    ['all the time', 'very often; constantly', 'постоянно'],
    ['now and then', 'sometimes, but not often', 'время от времени'],
    ['every now and again', 'occasionally', 'изредка'],
    ['rarely', 'not often', 'редко'],
    ['hardly ever', 'almost never', 'почти никогда'],
    ['not as a rule', 'usually not', 'как правило, нет'],
    ['tend to', 'to usually do something', 'иметь склонность, обычно делать'],
    ['used to', 'did regularly in the past (not now)', 'раньше (делал)'],
    ['not as much as I’d like to', 'less often than I want', 'не так часто, как хотелось бы']
  ]},
  { id: 'u1a5', title: 'p.9 ex.5 · Describing films, music and books', words: [
    ['astonishing', 'just incredible; amazing', 'поразительный'],
    ['catchy', 'easy to remember (a tune)', 'запоминающийся, прилипчивый'],
    ['commercial', 'typical big-budget, made to earn money', 'коммерческий'],
    ['disturbing', 'upsetting; makes you worried', 'тревожащий, неприятный'],
    ['dreadful', 'terrible; very bad', 'ужасный'],
    ['gripping', 'so exciting you can’t stop reading / watching', 'захватывающий'],
    ['hilarious', 'really, really funny', 'уморительный'],
    ['over-the-top', 'exaggerated; too extreme', 'чрезмерный, перебор'],
    ['uplifting', 'inspiring; makes you feel happier', 'воодушевляющий'],
    ['weird', 'strange; hard to explain', 'странный']
  ]},
  { id: 'u1pol', title: 'p.9 · Disagreeing politely', words: [
    ['to be honest, I’m not that keen on…', 'softer way to say “I don’t like…”', 'честно говоря, я не очень люблю…'],
    ['a bit too weird for my liking', 'softened negative opinion', 'немного странновато на мой вкус'],
    ['not really my kind of thing', 'I don’t really like this type of thing', 'не совсем в моём вкусе'],
    ['It was OK / not bad, I suppose / I guess, but…', 'weak agreement before disagreeing', 'нормально, наверное, но…'],
    ['As I say,…', 'repeating what you said before', 'как я уже сказал(а),…'],
    ['a bit', 'softens a negative adjective', 'немного, слегка']
  ]},
  { id: 'u1b', title: 'p.10 ex.6 · Plots', words: [
    ['tackle (an issue)', 'to deal with a problem or topic', 'затрагивать, браться за (проблему)'],
    ['twist', 'an unexpected change in a story', 'неожиданный поворот'],
    ['twists and turns', 'many surprising changes in a plot', 'сюжетные повороты'],
    ['remake', 'a new version of an older film', 'ремейк'],
    ['sequel', 'a film that continues the story of another', 'сиквел, продолжение'],
    ['smash (hit)', 'a hugely successful film or song', 'громкий хит, успех'],
    ['revolve around', 'to have as the main subject', 'вращаться вокруг, строиться на'],
    ['flaw', 'a fault or weakness', 'недостаток, изъян'],
    ['adaptation', 'a book or play made into a film / TV show', 'экранизация, адаптация'],
    ['shot (in…)', 'filmed (in a place)', 'снят(о) (где-то)'],
    ['cast', 'all the actors in a film or play', 'актёрский состав'],
    ['touch on', 'to mention briefly', 'слегка касаться (темы)'],
    ['classic / all-time classic', 'a film that is considered great for ever', 'классика'],
    ['an amazing cast', 'a group of excellent actors', 'потрясающий актёрский состав'],
    ['issue', 'an important topic or problem', 'проблема, вопрос']
  ]},
  { id: 'u1c', title: 'p.12 ex.3 · Talking about pictures', words: [
    ['bold', 'very bright, strong and clear (colours)', 'яркий, смелый'],
    ['subtle', 'not strong or bright; soft, delicate', 'тонкий, неброский'],
    ['conventional', 'traditional; not new or different', 'традиционный'],
    ['dramatic', 'containing a lot of exciting action', 'драматичный'],
    ['atmospheric', 'creates a special mood (romance, mystery)', 'атмосферный'],
    ['abstract', 'represents ideas or emotions, not real things', 'абстрактный'],
    ['realistic', 'shows people / objects in a photographic way', 'реалистичный'],
    ['ambiguous', 'meaning isn’t clear; open to interpretation', 'неоднозначный'],
    ['domestic', 'related to home and family', 'бытовой, домашний']
  ]},
  { id: 'u1c4', title: 'p.12 ex.4–5 · Describing what you see', words: [
    ['create a feeling of…', 'to make people feel something', 'создавать ощущение…'],
    ['look as if…', 'seem like it is true', 'выглядеть так, будто…'],
    ['obviously', 'in a way that is clear to see', 'очевидно'],
    ['seem to', 'to give the impression of', 'казаться'],
    ['appear to', 'to seem; to look like', 'по-видимому'],
    ['get the impression (that)', 'to have a feeling about something', 'создаётся впечатление'],
    ['look like', 'to be similar in appearance to', 'выглядеть как'],
    ['must be', 'I’m almost sure it is', 'должно быть'],
    ['could well be', 'it is quite possible', 'вполне может быть']
  ]},
  { id: 'm1', title: 'Moodle · A fabulous play', words: [
    ['spine-tingling', 'very frightening or exciting in a way you enjoy', 'мурашки по коже, будоражащий'],
    ['ghost story', 'a story about the spirit of a dead person', 'история с привидениями'],
    ['on the edge of your seat', 'very excited and interested', 'сидеть как на иголках'],
    ['set', 'scenery and furniture in a play or film', 'декорации'],
    ['sound effects', 'artificial sounds in a play or film', 'звуковые эффекты'],
    ['scare sb out of their wits', 'to frighten somebody very much', 'до смерти напугать'],
    ['nail-biting', 'making you very excited or worried (= gripping)', 'держащий в напряжении'],
    ['sensational', 'extremely good; wonderful', 'сенсационный, потрясающий'],
    ['applause', 'the sound of an audience clapping', 'аплодисменты'],
    ['applaud', 'to clap your hands to show approval', 'аплодировать'],
    ['phenomenally', 'in a very great or impressive way', 'феноменально'],
    ['unanimously', 'in a way that is agreed by everyone', 'единогласно'],
    ['acclaimed', 'publicly praised in an admiring way', 'получивший признание']
  ]},
  { id: 'm2', title: 'Moodle · A terrible movie', words: [
    ['atrocious', 'very bad and unpleasant (= dire)', 'отвратительный'],
    ['dire', 'very bad; terrible', 'ужасный, никудышный'],
    ['sentimental', 'making people feel sadness / sympathy in an obvious way', 'сентиментальный, слащавый'],
    ['cliché', 'an idea used so often it’s no longer interesting', 'клише, штамп'],
    ['clichéd', 'full of clichés', 'банальный, штампованный'],
    ['shallow', 'not showing serious thought or feelings (= superficial)', 'поверхностный'],
    ['feeble', 'very weak', 'слабый, беспомощный'],
    ['wooden', 'not showing natural expression or emotion', 'деревянный, безэмоциональный (игра)'],
    ['mediocre', 'of only average quality', 'посредственный'],
    ['miscast', 'an actor not suitable for the role', 'неподходящий на роль'],
    ['unconvincing', 'not seeming true or real', 'неубедительный'],
    ['utter', 'complete (used to emphasize something bad)', 'полный, абсолютный'],
    ['rubbish', 'something of very poor quality', 'ерунда, мусор'],
    ['tedious', 'boring (a synonym for “boring”)', 'нудный, скучный'],
    ['bored to tears / to death / stiff', 'very bored (idioms)', 'смертельно скучно']
  ]},
  { id: 'm3', title: 'Moodle · Crossword “Films”', words: [
    ['soundtrack', 'sound recording on a narrow strip of a motion picture film', 'саундтрек'],
    ['premiere', 'the first public performance of a play or movie', 'премьера'],
    ['director', 'the person who directs the making of a film', 'режиссёр'],
    ['producer', 'someone who finances and supervises the making of a show', 'продюсер'],
    ['critic', 'a person engaged in the analysis and interpretation of art', 'критик'],
    ['author', 'a person who is able to write and has written something', 'автор'],
    ['scene', 'series of pictures constituting a unit of action in a film', 'сцена'],
    ['actor', 'a performer in theatre, television, or film', 'актёр'],
    ['casting', 'assigning roles (of a movie or a play) to actors', 'подбор актёров, кастинг'],
    ['subtitles', 'translation of foreign dialogue of a movie or TV programme', 'субтитры'],
    ['dubbing', 'a new soundtrack that is added to a film', 'дубляж'],
    ['editor', 'the person who determines the final content of a text', 'редактор'],
    ['extra', 'a minor actor in crowd scenes', 'статист'],
    ['score', 'a written form of a musical composition', 'партитура, музыка к фильму'],
    ['manuscript', 'something written by hand', 'рукопись'],
    ['setting', 'scenery used to identify a location of a dramatic production', 'место действия, антураж']
  ]},

  /* ---------------- Unit 2 · Sightseeing ---------------- */
  { id: 'v2_14', title: 'p.14 ex.1 · Sightseeing activities', words: [
    ['go up a tower / ferris wheel for the view', 'to climb or ride up high to see the city', 'подняться на башню / колесо обозрения ради вида'],
    ['go on a bike / Segway / bus tour', 'to see a place on an organised ride', 'отправиться на велотур / сегвей-тур / автобусную экскурсию'],
    ['visit an unusual museum / monument', 'to see a different, interesting attraction', 'посетить необычный музей / памятник'],
    ['visit a temple / mosque / cathedral', 'to see a place of worship as a sight', 'посетить храм / мечеть / собор'],
    ['go to a theme park', 'to spend a day at an amusement park', 'сходить в тематический парк'],
    ['watch wildlife', 'to observe wild animals in nature', 'наблюдать за дикой природой']
  ]},
  { id: 'v2_15a', title: 'p.15 ex.1 · Buildings and areas', words: [
    ['residential', 'with mostly homes, not shops or offices', 'жилой (район)'],
    ['hideous', 'extremely ugly', 'отвратительный, безобразный'],
    ['monument', 'a building or statue that honours a person or event', 'памятник'],
    ['high-rise', 'a very tall building with many floors', 'высотка, многоэтажное здание'],
    ['wealthy', 'rich; having a lot of money', 'богатый, состоятельный'],
    ['historic', 'important in history', 'исторический, имеющий историческое значение'],
    ['rough', 'unpleasant or dangerous (an area)', 'неблагополучный, опасный (район)'],
    ['stunning', 'extremely attractive or impressive (syn. beautiful)', 'потрясающий, ошеломляющий'],
    ['trendy', 'fashionable at the moment', 'модный']
  ]},
  { id: 'v2_15b', title: 'p.15 ex.3 · Verbs about buildings', words: [
    ['base', 'to have your main office or home in a place', 'базироваться, иметь штаб-квартиру'],
    ['date back', 'to have existed since a time in the past', 'восходить к, насчитывать (какой-то) возраст'],
    ['do up', 'to repair and improve (a building)', 'отремонтировать, привести в порядок'],
    ['keep an eye on', 'to watch carefully', 'присматривать за'],
    ['knock down', 'to demolish a building', 'снести (здание)'],
    ['open up', 'to start business; to appear (shops, cafés)', 'открываться, появляться']
  ]},
  { id: 'v2_18a', title: 'p.18 ex.2 · Festivals and carnivals', words: [
    ['bonfire', 'a large fire built outdoors', 'костёр'],
    ['celebrations', 'events held for a special occasion', 'празднования'],
    ['costume', 'clothes worn for a party or a role', 'костюм'],
    ['fireworks', 'explosives that make coloured lights in the sky', 'фейерверк'],
    ['float', 'a decorated vehicle in a parade', 'карнавальная платформа, колесница'],
    ['mask', 'something that covers your face', 'маска'],
    ['parade', 'people moving through the streets in a procession', 'парад, шествие'],
    ['sound system', 'loudspeakers and equipment for playing music', 'звуковая аппаратура']
  ]},
  { id: 'v2_18b', title: 'p.18 ex.3 · Festival collocations', words: [
    ['wear a mask / hide behind a mask', 'to cover your face', 'надеть маску / прятаться за маской'],
    ['take part in a parade / a parade through town', 'to join a procession', 'участвовать в параде / парад по городу'],
    ['ride on a float / decorate a float', 'to use a parade vehicle', 'ехать на платформе / украшать платформу'],
    ['set up a sound system / a really loud sound system', 'to prepare music equipment', 'установить звуковую аппаратуру / очень громкая аппаратура'],
    ['make a costume / hire a fancy dress costume', 'to get something to dress up in', 'сшить костюм / взять напрокат маскарадный костюм'],
    ['sit round a bonfire / throw wood on a bonfire', 'to be at, or feed, an outdoor fire', 'сидеть у костра / подбросить дров в костёр'],
    ['take part in celebrations', 'to join in a festival', 'участвовать в празднованиях'],
    ['set off fireworks / watch a fireworks display', 'to launch, or see, fireworks', 'запускать фейерверк / смотреть фейерверк']
  ]},
  { id: 'v2_19', title: 'p.19 · Party round the world', words: [
    ['caricatured', 'made fun of by exaggerating features', 'высмеивал, изображал в виде карикатуры'],
    ['blast out', 'to play loudly (music)', 'греметь, громко играть'],
    ['reef', 'a line of rocks or coral in the sea', 'риф'],
    ['kick off', 'to start (an event)', 'начинаться (о мероприятии)'],
    ['mock', 'not real; playful, pretend', 'ненастоящий, шуточный'],
    ['passers-by', 'people walking past a place', 'прохожие'],
    ['lounge', 'to stand, sit or lie in a relaxed way', 'отдыхать, развалиться'],
    ['culminate', 'to reach the end or final point', 'достигать кульминации']
  ]},
  { id: 'v2_gl', title: 'Moodle · I can talk about holidays', words: [
    ['thriving', 'growing and developing; very successful (syn. flourishing)', 'процветающий'],
    ['vibrant', 'full of life and energy', 'яркий, полный жизни'],
    ['cobbled streets', 'streets covered with old round stones', 'мощёные улицы, булыжная мостовая'],
    ['remarkably', 'in an unusual or surprising way', 'удивительно, на редкость'],
    ['diverse', 'of many different kinds', 'разнообразный'],
    ['undergo sth', 'to experience a process of change', 'проходить через, подвергаться (изменению)'],
    ['restoration', 'the work of repairing old buildings, paintings, etc.', 'реставрация'],
    ['laze around', 'to relax and do very little', 'бездельничать, лениться'],
    ['soak sth up', 'to absorb something into your senses, body or mind', 'впитывать (атмосферу)'],
    ['go for a wander (around / in)', 'to walk slowly without a real purpose', 'пойти побродить'],
    ['retain sth', 'to keep something (formal)', 'сохранять'],
    ['charm', 'a pleasant or attractive quality', 'очарование, шарм'],
    ['off the beaten track', 'far away from other people and houses', 'в стороне от туристических троп'],
    ['trek', 'a long, hard walk, often in the mountains', 'поход, трек'],
    ['unique', 'the only one of its kind', 'уникальный'],
    ['get away from it all', 'to go somewhere different for a rest or holiday', 'уехать от всего, отключиться от суеты'],
    ['remote', 'far from places where other people live (syn. isolated)', 'отдалённый, глухой'],
    ['unspoilt', 'beautiful because it has not been changed or built on', 'нетронутый, не испорченный цивилизацией']
  ]},
  { id: 'v2_tg', title: 'Moodle · Travel Guide: St. Petersburg', words: [
    ['nestled on', 'located in a sheltered, pleasant place', 'расположенный, уютно раскинувшийся на'],
    ['spread out', 'to cover a wide area', 'раскинуться'],
    ['delta', 'the area where a river divides before the sea', 'дельта'],
    ['extravagant', 'very expensive and impressive; luxurious', 'роскошный, помпезный'],
    ['breathtaking', 'so beautiful that it surprises you', 'захватывающий дух'],
    ['grandiose', 'big and impressive', 'грандиозный'],
    ['picturesque', 'attractive in a way that looks like a picture', 'живописный'],
    ['gilded', 'covered with a thin layer of gold', 'позолоченный'],
    ['rival', 'to be as good as something else', 'соперничать с'],
    ['monumental', 'very large and impressive', 'монументальный'],
    ['legacy', 'something left by people of the past', 'наследие'],
    ['spire', 'a tall pointed top of a building', 'шпиль'],
    ['dome', 'a round roof of a building', 'купол'],
    ['gateway', 'a place that gives access to another region', 'ворота, выход (к морю)'],
    ['citadel', 'a fortress protecting a city', 'цитадель'],
    ['sumptuous', 'splendid and obviously very expensive', 'великолепный, роскошный'],
    ['hydrofoil', 'a fast boat that rises above the water', 'судно на подводных крыльях'],
    ['intrigue', 'secret plans to get power or harm somebody', 'интриги'],
    ['opulent', 'rich and luxurious', 'пышный, богатый'],
    ['drawbridge', 'a bridge that can be raised to let boats pass', 'разводной мост'],
    ['a glittering testament to', 'a shining proof of something', 'блестящее свидетельство чего-либо']
  ]},
  { id: 'v2_rel', title: 'Moodle · Spotlight: relax', words: [
    ['unwind', 'to relax after work or stress', 'расслабиться, отдохнуть'],
    ['take it easy', 'to relax and not work hard (informal)', 'не напрягаться, расслабиться'],
    ['chill out', 'to relax completely (informal)', 'расслабиться, «охладиться»'],
    ['recharge your batteries', 'to get your energy back on a break (idiom)', 'восстановить силы, «перезарядиться»']
  ]},
  { id: 'v2_202a', title: 'p.202 track · Lesson 2A: Belgrade tour', words: [
    ['entertainment venue', 'a place where concerts and sports events are held', 'место проведения концертов и мероприятий'],
    ['waterside', 'the land beside a river or the sea', 'набережная, берег'],
    ['light up', 'to fill with light; to illuminate at night', 'подсвечивать, освещать'],
    ['landmark', 'a famous building or place that is easy to recognise', 'знаковая достопримечательность'],
    ['tomb', 'a place where a dead person is buried', 'гробница, усыпальница'],
    ['emperor', 'the ruler of an empire', 'император'],
    ['embassy', 'the official office of one country in another', 'посольство'],
    ['site', 'the place where something was built or happened', 'место, участок (где стоит здание)'],
    ['aristocratic', 'belonging to the highest social class', 'аристократический'],
    ['celebrity', 'a famous person', 'знаменитость'],
    ['fortress', 'a strong building used for defence', 'крепость']
  ]},
  { id: 'v2_202b', title: 'p.202 track · Lesson 2C: listening', words: [
    ['a waste of money', 'a bad use of money', 'пустая трата денег'],
    ['insist', 'to say firmly that something must happen', 'настаивать'],
    ['give in', 'to stop resisting and agree', 'сдаться, уступить'],
    ['afford', 'to have enough money to pay for something', 'позволить себе (по деньгам)'],
    ['put in an offer', 'to offer a price for a property', 'сделать предложение о цене'],
    ['competitive market', 'a market where many buyers compete', 'конкурентный рынок'],
    ['bound to', 'certain to happen', 'непременно, обязательно'],
    ['opposition', 'people who disagree with a plan', 'противодействие, оппозиция'],
    ['protester', 'a person who publicly shows disagreement', 'протестующий'],
    ['due to be approved', 'expected to be officially accepted', 'должен быть одобрен'],
    ['vintage vehicles', 'old cars that are valued for their quality', 'раритетные автомобили'],
    ['restricted numbers', 'a limited amount of tickets or places', 'ограниченное количество'],
    ['sell out', 'to sell all of the tickets', 'распродаться']
  ]}
];
