/* Слова для устного английского (Шкода Ю.Д.) — Unit 1 Entertainment, Unit 2 Sightseeing.
   Один источник данных: его читают и words.html, и окно прогресса в app.js.
   Формат слова: [слово, значение по-английски, перевод]. Слово = уникальный id (не повторять между группами).
   Группы Unit 2 имеют id с префиксом v2 — по нему words.html относит их к категории «Vocabulary U.2». */
window.EN_WORDS = [
  { id: 'u1a', title: 'p.8–9 · Привычки (Habits)', words: [
    ['all the time', 'very often; constantly', 'постоянно'],
    ['now and then', 'sometimes, but not often', 'время от времени'],
    ['every now and again', 'occasionally', 'изредка'],
    ['rarely', 'not often', 'редко'],
    ['hardly ever', 'almost never', 'почти никогда'],
    ['not as a rule', 'usually not', 'как правило, нет'],
    ['tend to', 'to usually do something', 'иметь склонность, обычно делать'],
    ['used to', 'did regularly in the past (not now)', 'раньше (делал)'],
    ['not as much as I’d like to', 'less often than I want', 'не так часто, как хотелось бы']
  ]},
  { id: 'u1a5', title: 'p.9 ex.5 · Describing films, music and books', words: [
    ['astonishing', 'just incredible; amazing', 'поразительный'],
    ['catchy', 'easy to remember (a tune)', 'запоминающийся, прилипчивый'],
    ['commercial', 'typical big-budget, made to earn money', 'коммерческий'],
    ['disturbing', 'upsetting; makes you worried', 'тревожащий, неприятный'],
    ['dreadful', 'terrible; very bad', 'ужасный'],
    ['gripping', 'so exciting you can’t stop reading / watching', 'захватывающий'],
    ['hilarious', 'really, really funny', 'уморительный'],
    ['over-the-top', 'exaggerated; too extreme', 'чрезмерный, перебор'],
    ['uplifting', 'inspiring; makes you feel happier', 'воодушевляющий'],
    ['weird', 'strange; hard to explain', 'странный']
  ]},
  { id: 'u1pol', title: 'p.9 · Disagreeing politely', words: [
    ['to be honest, I’m not that keen on…', 'softer way to say “I don’t like…”', 'честно говоря, я не очень люблю…'],
    ['a bit too weird for my liking', 'softened negative opinion', 'немного странновато на мой вкус'],
    ['not really my kind of thing', 'I don’t really like this type of thing', 'не совсем в моём вкусе'],
    ['It was OK / not bad, I suppose / I guess, but…', 'weak agreement before disagreeing', 'нормально, наверное, но…'],
    ['As I say,…', 'repeating what you said before', 'как я уже сказал(а),…'],
    ['a bit', 'softens a negative adjective', 'немного, слегка']
  ]},
  { id: 'u1b', title: 'p.10 ex.6 · Plots', words: [
    ['tackle (an issue)', 'to deal with a problem or topic', 'затрагивать, браться за (проблему)'],
    ['twist', 'an unexpected change in a story', 'неожиданный поворот'],
    ['twists and turns', 'many surprising changes in a plot', 'сюжетные повороты'],
    ['remake', 'a new version of an older film', 'ремейк'],
    ['sequel', 'a film that continues the story of another', 'сиквел, продолжение'],
    ['smash (hit)', 'a hugely successful film or song', 'громкий хит, успех'],
    ['revolve around', 'to have as the main subject', 'вращаться вокруг, строиться на'],
    ['flaw', 'a fault or weakness', 'недостаток, изъян'],
    ['adaptation', 'a book or play made into a film / TV show', 'экранизация, адаптация'],
    ['shot (in…)', 'filmed (in a place)', 'снят(о) (где-то)'],
    ['cast', 'all the actors in a film or play', 'актёрский состав'],
    ['touch on', 'to mention briefly', 'слегка касаться (темы)'],
    ['classic / all-time classic', 'a film that is considered great for ever', 'классика'],
    ['an amazing cast', 'a group of excellent actors', 'потрясающий актёрский состав'],
    ['issue', 'an important topic or problem', 'проблема, вопрос']
  ]},
  { id: 'u1c', title: 'p.12 ex.3 · Talking about pictures', words: [
    ['bold', 'very bright, strong and clear (colours)', 'яркий, смелый'],
    ['subtle', 'not strong or bright; soft, delicate', 'тонкий, неброский'],
    ['conventional', 'traditional; not new or different', 'традиционный'],
    ['dramatic', 'containing a lot of exciting action', 'драматичный'],
    ['atmospheric', 'creates a special mood (romance, mystery)', 'атмосферный'],
    ['abstract', 'represents ideas or emotions, not real things', 'абстрактный'],
    ['realistic', 'shows people / objects in a photographic way', 'реалистичный'],
    ['ambiguous', 'meaning isn’t clear; open to interpretation', 'неоднозначный'],
    ['domestic', 'related to home and family', 'бытовой, домашний']
  ]},
  { id: 'u1c4', title: 'p.12 ex.4–5 · Describing what you see', words: [
    ['create a feeling of…', 'to make people feel something', 'создавать ощущение…'],
    ['look as if…', 'seem like it is true', 'выглядеть так, будто…'],
    ['obviously', 'in a way that is clear to see', 'очевидно'],
    ['seem to', 'to give the impression of', 'казаться'],
    ['appear to', 'to seem; to look like', 'по-видимому'],
    ['get the impression (that)', 'to have a feeling about something', 'создаётся впечатление'],
    ['look like', 'to be similar in appearance to', 'выглядеть как'],
    ['must be', 'I’m almost sure it is', 'должно быть'],
    ['could well be', 'it is quite possible', 'вполне может быть']
  ]},
  { id: 'm1', title: 'Moodle · A fabulous play', words: [
    ['spine-tingling', 'very frightening or exciting in a way you enjoy', 'мурашки по коже, будоражащий'],
    ['ghost story', 'a story about the spirit of a dead person', 'история с привидениями'],
    ['on the edge of your seat', 'very excited and interested', 'сидеть как на иголках'],
    ['set', 'scenery and furniture in a play or film', 'декорации'],
    ['sound effects', 'artificial sounds in a play or film', 'звуковые эффекты'],
    ['scare sb out of their wits', 'to frighten somebody very much', 'до смерти напугать'],
    ['nail-biting', 'making you very excited or worried (= gripping)', 'держащий в напряжении'],
    ['sensational', 'extremely good; wonderful', 'сенсационный, потрясающий'],
    ['applause', 'the sound of an audience clapping', 'аплодисменты'],
    ['applaud', 'to clap your hands to show approval', 'аплодировать'],
    ['phenomenally', 'in a very great or impressive way', 'феноменально'],
    ['unanimously', 'in a way that is agreed by everyone', 'единогласно'],
    ['acclaimed', 'publicly praised in an admiring way', 'получивший признание']
  ]},
  { id: 'm2', title: 'Moodle · A terrible movie', words: [
    ['atrocious', 'very bad and unpleasant (= dire)', 'отвратительный'],
    ['dire', 'very bad; terrible', 'ужасный, никудышный'],
    ['sentimental', 'making people feel sadness / sympathy in an obvious way', 'сентиментальный, слащавый'],
    ['cliché', 'an idea used so often it’s no longer interesting', 'клише, штамп'],
    ['clichéd', 'full of clichés', 'банальный, штампованный'],
    ['shallow', 'not showing serious thought or feelings (= superficial)', 'поверхностный'],
    ['feeble', 'very weak', 'слабый, беспомощный'],
    ['wooden', 'not showing natural expression or emotion', 'деревянный, безэмоциональный (игра)'],
    ['mediocre', 'of only average quality', 'посредственный'],
    ['miscast', 'an actor not suitable for the role', 'неподходящий на роль'],
    ['unconvincing', 'not seeming true or real', 'неубедительный'],
    ['utter', 'complete (used to emphasize something bad)', 'полный, абсолютный'],
    ['rubbish', 'something of very poor quality', 'ерунда, мусор'],
    ['tedious', 'boring (a synonym for “boring”)', 'нудный, скучный'],
    ['bored to tears / to death / stiff', 'very bored (idioms)', 'смертельно скучно']
  ]},
  { id: 'm3', title: 'Moodle · Crossword “Films”', words: [
    ['soundtrack', 'sound recording on a narrow strip of a motion picture film', 'саундтрек'],
    ['premiere', 'the first public performance of a play or movie', 'премьера'],
    ['director', 'the person who directs the making of a film', 'режиссёр'],
    ['producer', 'someone who finances and supervises the making of a show', 'продюсер'],
    ['critic', 'a person engaged in the analysis and interpretation of art', 'критик'],
    ['author', 'a person who is able to write and has written something', 'автор'],
    ['scene', 'series of pictures constituting a unit of action in a film', 'сцена'],
    ['actor', 'a performer in theatre, television, or film', 'актёр'],
    ['casting', 'assigning roles (of a movie or a play) to actors', 'подбор актёров, кастинг'],
    ['subtitles', 'translation of foreign dialogue of a movie or TV programme', 'субтитры'],
    ['dubbing', 'a new soundtrack that is added to a film', 'дубляж'],
    ['editor', 'the person who determines the final content of a text', 'редактор'],
    ['extra', 'a minor actor in crowd scenes', 'статист'],
    ['score', 'a written form of a musical composition', 'партитура, музыка к фильму'],
    ['manuscript', 'something written by hand', 'рукопись'],
    ['setting', 'scenery used to identify a location of a dramatic production', 'место действия, антураж']
  ]},

  /* ---------------- Unit 2 · Sightseeing ---------------- */
  { id: 'v2_14', title: 'p.14 ex.1 · Sightseeing activities', words: [
    ['go up a tower / ferris wheel for the view', 'to climb or ride up high to see the city', 'подняться на башню / колесо обозрения ради вида'],
    ['go on a bike / Segway / bus tour', 'to see a place on an organised ride', 'отправиться на велотур / сегвей-тур / автобусную экскурсию'],
    ['visit an unusual museum / monument', 'to see a different, interesting attraction', 'посетить необычный музей / памятник'],
    ['visit a temple / mosque / cathedral', 'to see a place of worship as a sight', 'посетить храм / мечеть / собор'],
    ['go to a theme park', 'to spend a day at an amusement park', 'сходить в тематический парк'],
    ['watch wildlife', 'to observe wild animals in nature', 'наблюдать за дикой природой']
  ]},
  { id: 'v2_15a', title: 'p.15 ex.1 · Buildings and areas', words: [
    ['residential', 'with mostly homes, not shops or offices', 'жилой (район)'],
    ['hideous', 'extremely ugly', 'отвратительный, безобразный'],
    ['monument', 'a building or statue that honours a person or event', 'памятник'],
    ['high-rise', 'a very tall building with many floors', 'высотка, многоэтажное здание'],
    ['wealthy', 'rich; having a lot of money', 'богатый, состоятельный'],
    ['historic', 'important in history', 'исторический, имеющий историческое значение'],
    ['rough', 'unpleasant or dangerous (an area)', 'неблагополучный, опасный (район)'],
    ['stunning', 'extremely attractive or impressive (syn. beautiful)', 'потрясающий, ошеломляющий'],
    ['trendy', 'fashionable at the moment', 'модный']
  ]},
  { id: 'v2_15b', title: 'p.15 ex.3 · Verbs about buildings', words: [
    ['base', 'to have your main office or home in a place', 'базироваться, иметь штаб-квартиру'],
    ['date back', 'to have existed since a time in the past', 'восходить к, насчитывать (какой-то) возраст'],
    ['do up', 'to repair and improve (a building)', 'отремонтировать, привести в порядок'],
    ['keep an eye on', 'to watch carefully', 'присматривать за'],
    ['knock down', 'to demolish a building', 'снести (здание)'],
    ['open up', 'to start business; to appear (shops, cafés)', 'открываться, появляться']
  ]},
  { id: 'v2_18a', title: 'p.18 ex.2 · Festivals and carnivals', words: [
    ['bonfire', 'a large fire built outdoors', 'костёр'],
    ['celebrations', 'events held for a special occasion', 'празднования'],
    ['costume', 'clothes worn for a party or a role', 'костюм'],
    ['fireworks', 'explosives that make coloured lights in the sky', 'фейерверк'],
    ['float', 'a decorated vehicle in a parade', 'карнавальная платформа, колесница'],
    ['mask', 'something that covers your face', 'маска'],
    ['parade', 'people moving through the streets in a procession', 'парад, шествие'],
    ['sound system', 'loudspeakers and equipment for playing music', 'звуковая аппаратура']
  ]},
  { id: 'v2_18b', title: 'p.18 ex.3 · Festival collocations', words: [
    ['wear a mask / hide behind a mask', 'to cover your face', 'надеть маску / прятаться за маской'],
    ['take part in a parade / a parade through town', 'to join a procession', 'участвовать в параде / парад по городу'],
    ['ride on a float / decorate a float', 'to use a parade vehicle', 'ехать на платформе / украшать платформу'],
    ['set up a sound system / a really loud sound system', 'to prepare music equipment', 'установить звуковую аппаратуру / очень громкая аппаратура'],
    ['make a costume / hire a fancy dress costume', 'to get something to dress up in', 'сшить костюм / взять напрокат маскарадный костюм'],
    ['sit round a bonfire / throw wood on a bonfire', 'to be at, or feed, an outdoor fire', 'сидеть у костра / подбросить дров в костёр'],
    ['take part in celebrations', 'to join in a festival', 'участвовать в празднованиях'],
    ['set off fireworks / watch a fireworks display', 'to launch, or see, fireworks', 'запускать фейерверк / смотреть фейерверк']
  ]},
  { id: 'v2_19', title: 'p.19 · Party round the world', words: [
    ['caricatured', 'made fun of by exaggerating features', 'высмеивал, изображал в виде карикатуры'],
    ['blast out', 'to play loudly (music)', 'греметь, громко играть'],
    ['reef', 'a line of rocks or coral in the sea', 'риф'],
    ['kick off', 'to start (an event)', 'начинаться (о мероприятии)'],
    ['mock', 'not real; playful, pretend', 'ненастоящий, шуточный'],
    ['passers-by', 'people walking past a place', 'прохожие'],
    ['lounge', 'to stand, sit or lie in a relaxed way', 'отдыхать, развалиться'],
    ['culminate', 'to reach the end or final point', 'достигать кульминации']
  ]},
  { id: 'v2_gl', title: 'Moodle · I can talk about holidays', words: [
    ['thriving', 'growing and developing; very successful (syn. flourishing)', 'процветающий'],
    ['vibrant', 'full of life and energy', 'яркий, полный жизни'],
    ['cobbled streets', 'streets covered with old round stones', 'мощёные улицы, булыжная мостовая'],
    ['remarkably', 'in an unusual or surprising way', 'удивительно, на редкость'],
    ['diverse', 'of many different kinds', 'разнообразный'],
    ['undergo sth', 'to experience a process of change', 'проходить через, подвергаться (изменению)'],
    ['restoration', 'the work of repairing old buildings, paintings, etc.', 'реставрация'],
    ['laze around', 'to relax and do very little', 'бездельничать, лениться'],
    ['soak sth up', 'to absorb something into your senses, body or mind', 'впитывать (атмосферу)'],
    ['go for a wander (around / in)', 'to walk slowly without a real purpose', 'пойти побродить'],
    ['retain sth', 'to keep something (formal)', 'сохранять'],
    ['charm', 'a pleasant or attractive quality', 'очарование, шарм'],
    ['off the beaten track', 'far away from other people and houses', 'в стороне от туристических троп'],
    ['trek', 'a long, hard walk, often in the mountains', 'поход, трек'],
    ['unique', 'the only one of its kind', 'уникальный'],
    ['get away from it all', 'to go somewhere different for a rest or holiday', 'уехать от всего, отключиться от суеты'],
    ['remote', 'far from places where other people live (syn. isolated)', 'отдалённый, глухой'],
    ['unspoilt', 'beautiful because it has not been changed or built on', 'нетронутый, не испорченный цивилизацией']
  ]},
  { id: 'v2_tg', title: 'Moodle · Travel Guide: St. Petersburg', words: [
    ['nestled on', 'located in a sheltered, pleasant place', 'расположенный, уютно раскинувшийся на'],
    ['spread out', 'to cover a wide area', 'раскинуться'],
    ['delta', 'the area where a river divides before the sea', 'дельта'],
    ['extravagant', 'very expensive and impressive; luxurious', 'роскошный, помпезный'],
    ['breathtaking', 'so beautiful that it surprises you', 'захватывающий дух'],
    ['grandiose', 'big and impressive', 'грандиозный'],
    ['picturesque', 'attractive in a way that looks like a picture', 'живописный'],
    ['gilded', 'covered with a thin layer of gold', 'позолоченный'],
    ['rival', 'to be as good as something else', 'соперничать с'],
    ['monumental', 'very large and impressive', 'монументальный'],
    ['legacy', 'something left by people of the past', 'наследие'],
    ['spire', 'a tall pointed top of a building', 'шпиль'],
    ['dome', 'a round roof of a building', 'купол'],
    ['gateway', 'a place that gives access to another region', 'ворота, выход (к морю)'],
    ['citadel', 'a fortress protecting a city', 'цитадель'],
    ['sumptuous', 'splendid and obviously very expensive', 'великолепный, роскошный'],
    ['hydrofoil', 'a fast boat that rises above the water', 'судно на подводных крыльях'],
    ['intrigue', 'secret plans to get power or harm somebody', 'интриги'],
    ['opulent', 'rich and luxurious', 'пышный, богатый'],
    ['drawbridge', 'a bridge that can be raised to let boats pass', 'разводной мост'],
    ['a glittering testament to', 'a shining proof of something', 'блестящее свидетельство чего-либо']
  ]},
  { id: 'v2_rel', title: 'Moodle · Spotlight: relax', words: [
    ['unwind', 'to relax after work or stress', 'расслабиться, отдохнуть'],
    ['take it easy', 'to relax and not work hard (informal)', 'не напрягаться, расслабиться'],
    ['chill out', 'to relax completely (informal)', 'расслабиться, «охладиться»'],
    ['recharge your batteries', 'to get your energy back on a break (idiom)', 'восстановить силы, «перезарядиться»']
  ]},
  { id: 'v2_202a', title: 'p.202 track · Lesson 2A: Belgrade tour', words: [
    ['entertainment venue', 'a place where concerts and sports events are held', 'место проведения концертов и мероприятий'],
    ['waterside', 'the land beside a river or the sea', 'набережная, берег'],
    ['light up', 'to fill with light; to illuminate at night', 'подсвечивать, освещать'],
    ['landmark', 'a famous building or place that is easy to recognise', 'знаковая достопримечательность'],
    ['tomb', 'a place where a dead person is buried', 'гробница, усыпальница'],
    ['emperor', 'the ruler of an empire', 'император'],
    ['embassy', 'the official office of one country in another', 'посольство'],
    ['site', 'the place where something was built or happened', 'место, участок (где стоит здание)'],
    ['aristocratic', 'belonging to the highest social class', 'аристократический'],
    ['celebrity', 'a famous person', 'знаменитость'],
    ['fortress', 'a strong building used for defence', 'крепость']
  ]},
  { id: 'v2_202b', title: 'p.202 track · Lesson 2C: listening', words: [
    ['a waste of money', 'a bad use of money', 'пустая трата денег'],
    ['insist', 'to say firmly that something must happen', 'настаивать'],
    ['give in', 'to stop resisting and agree', 'сдаться, уступить'],
    ['afford', 'to have enough money to pay for something', 'позволить себе (по деньгам)'],
    ['put in an offer', 'to offer a price for a property', 'сделать предложение о цене'],
    ['competitive market', 'a market where many buyers compete', 'конкурентный рынок'],
    ['bound to', 'certain to happen', 'непременно, обязательно'],
    ['opposition', 'people who disagree with a plan', 'противодействие, оппозиция'],
    ['protester', 'a person who publicly shows disagreement', 'протестующий'],
    ['due to be approved', 'expected to be officially accepted', 'должен быть одобрен'],
    ['vintage vehicles', 'old cars that are valued for their quality', 'раритетные автомобили'],
    ['restricted numbers', 'a limited amount of tickets or places', 'ограниченное количество'],
    ['sell out', 'to sell all of the tickets', 'распродаться']
  ]},

  /* ---------------- Unit 3 · Things you need ---------------- */
  { id: 'v3_192', title: 'p.192 file 3 · Useful things', words: [
    ['a hammer', 'a tool for hitting nails into things', 'молоток'],
    ['a drill', 'a tool for making holes', 'дрель'],
    ['a saw', 'a tool with a sharp edge for cutting wood', 'пила'],
    ['a torch', 'a small electric light you carry in your hand', 'фонарик'],
    ['a stepladder', 'a short ladder that stands on its own', 'стремянка'],
    ['a nail', 'a thin pointed piece of metal hit into wood', 'гвоздь'],
    ['a screw', 'a metal pin with a spiral line, turned into wood', 'шуруп'],
    ['toothpaste', 'a paste you put on a brush to clean your teeth', 'зубная паста'],
    ['a rope', 'very thick, strong string', 'верёвка, канат'],
    ['wire', 'thin metal thread', 'проволока'],
    ['a pan', 'a round metal container for cooking food', 'сковорода, кастрюля'],
    ['a cloth', 'a piece of material for cleaning or wiping', 'тряпка'],
    ['a dustpan and brush', 'tools for sweeping dirt off the floor', 'совок и щётка'],
    ['a mop and bucket', 'tools for washing the floor', 'швабра и ведро'],
    ['glue', 'a sticky liquid for joining things', 'клей'],
    ['a corkscrew', 'a tool for opening wine bottles', 'штопор'],
    ['a tin opener', 'a tool for opening cans', 'консервный нож'],
    ['a lighter', 'a small device that makes a flame', 'зажигалка'],
    ['a rubber', 'a small piece of rubber for removing pencil marks', 'ластик'],
    ['correction fluid', 'white liquid for covering mistakes in writing', 'корректирующая жидкость'],
    ['a stapler', 'a device that fixes papers together with small metal pieces', 'степлер'],
    ['scissors', 'a tool with two blades for cutting paper', 'ножницы'],
    ['clips', 'small objects that hold things together', 'скрепки, зажимы'],
    ['sticky tape', 'clear tape used to stick things together', 'скотч'],
    ['washing powder', 'powder for washing clothes', 'стиральный порошок'],
    ['an iron', 'an electric tool for making clothes flat and smooth', 'утюг'],
    ['a needle and thread', 'things used for sewing', 'иголка с ниткой'],
    ['clothes pegs', 'small clips for hanging washing on a line', 'прищепки'],
    ['a charger', 'a device for putting electricity into a battery', 'зарядное устройство'],
    ['a ruler', 'a flat tool for measuring and drawing straight lines', 'линейка'],
    ['a plaster', 'a small sticky cover for a small cut', 'пластырь'],
    ['a bandage', 'a long strip of cloth to cover a wound', 'бинт']
  ]},
  { id: 'v3_28', title: 'p.28 ex.4 · Fixing and cleaning', words: [
    ['put up (posters)', 'to fix something on a wall', 'вешать (плакаты)'],
    ['make a hole in the wall', 'to make an opening in a wall', 'сделать отверстие в стене'],
    ['clear up (spilled coffee)', 'to clean a mess', 'убрать (пролитый кофе)'],
    ['spill', 'to let a liquid fall out by accident', 'проливать'],
    ['mend', 'to repair something', 'чинить'],
    ['a tear (in your clothes)', 'a hole made by pulling cloth apart', 'прореха, дырка (в одежде)'],
    ['a packet of flour', 'a small paper or plastic bag of flour', 'пачка муки'],
    ['cut a tree down', 'to make a tree fall by cutting it', 'срубить дерево'],
    ['a leaking roof', 'a roof that lets water through', 'протекающая крыша'],
    ['a small cut', 'a little wound in your skin', 'небольшой порез'],
    ['smash', 'to break noisily into many pieces', 'разбиться вдребезги'],
    ['It’s (used) for…', 'explains what an object is for', 'это (используется) для…'],
    ['in order to', 'for the purpose of', 'для того чтобы'],
    ['so I can…', 'to explain a specific reason', 'чтобы я мог…']
  ]},
  { id: 'v3_29', title: 'p.29 ex.7 · Explaining and checking', words: [
    ['Blu Tack', 'sticky putty for fixing posters to a wall', 'клейкая масса для крепления плакатов'],
    ['a carabiner', 'a metal clip with a hook that opens and shuts', 'карабин'],
    ['a padlock', 'a lock you can hang on something', 'навесной замок'],
    ['a safety pin', 'a pin with a cover over its point', 'булавка'],
    ['a drawing pin', 'a short pin with a flat head for fixing paper', 'кнопка'],
    ['chewing gum', 'sweet stuff you chew but do not swallow', 'жевательная резинка'],
    ['key ring', 'a ring that holds your keys together', 'брелок, кольцо для ключей'],
    ['a hook', 'a curved piece of metal for hanging things', 'крючок'],
    ['stuff', 'informal word for things or material', 'вещь, штука, материал'],
    ['a bit like…', 'to explain with a comparison', 'немного похоже на…'],
    ['a sort of … thing', 'to explain when you don’t know the word', 'что-то вроде…'],
    ['Can you be a bit more specific?', 'asking for more detail', 'можете уточнить?'],
    ['You mean…?', 'checking you understand', 'вы имеете в виду…?'],
    ['the thing you use to…', 'to explain what something is for', 'штука, которой делают…']
  ]},
  { id: 'v3_30a', title: 'p.30 ex.1–2 · Tidiness and collecting', words: [
    ['obsessed with', 'thinking about something all the time', 'одержимый'],
    ['untidy', 'not neat; in a mess', 'неопрятный, неубранный'],
    ['dump', 'to leave things carelessly in a place', 'свалить, бросить как попало'],
    ['throw away', 'to put in the rubbish bin', 'выбрасывать'],
    ['get rid of', 'to remove or throw away', 'избавиться от'],
    ['acquire', 'to get something, often by buying', 'приобретать'],
    ['attached', 'having an emotional connection (be attached to sth)', 'привязанный'],
    ['collect', 'to bring together things of one type as a hobby', 'коллекционировать'],
    ['psychology', 'the study of the mind and behaviour', 'психология'],
    ['store', 'to keep for future use', 'хранить'],
    ['value', 'how much something is worth or important', 'ценность']
  ]},
  { id: 'v3_30b', title: 'p.30 ex.5 · Blog: collecting or hoarding', words: [
    ['hoarding', 'keeping too many things that you don’t need', 'накопительство, патологическое хранение'],
    ['hoarder', 'a person who keeps too many useless things', 'человек, копящий хлам'],
    ['a fine line', 'a small difference between two things', 'тонкая грань'],
    ['genuine', 'real; not pretending', 'настоящий, подлинный'],
    ['distress', 'great worry or unhappiness', 'страдание, тревога'],
    ['ashamed', 'feeling embarrassed about something you did or are', 'пристыженный'],
    ['storage space', 'room for keeping things', 'место для хранения'],
    ['shelving', 'a set of shelves', 'стеллажи, полки'],
    ['a health hazard', 'something that may harm your health', 'угроза здоровью'],
    ['navel fluff', 'the little balls of cotton in your belly button', 'пух из пупка'],
    ['autograph', 'a famous person’s signature', 'автограф'],
    ['unboxing', 'a video of opening a new product', 'распаковка']
  ]},
  { id: 'v3_30c', title: 'p.30 ex.7 · Collecting things', words: [
    ['curiosity', 'a strong wish to know about something', 'любопытство'],
    ['impressive', 'making you admire it', 'впечатляющий'],
    ['keen', 'very interested and enthusiastic', 'увлечённый, заядлый'],
    ['trade', 'to exchange things with someone', 'обмениваться, торговать'],
    ['swap', 'to exchange one thing for another', 'меняться'],
    ['get into', 'to start being interested in', 'увлечься'],
    ['passion', 'a very strong interest or feeling', 'страсть, увлечение'],
    ['junk', 'old things that have little value', 'хлам'],
    ['bid', 'to offer a price at an auction', 'делать ставку (на аукционе)'],
    ['pride', 'a feeling of satisfaction about your achievements', 'гордость'],
    ['show off', 'to display proudly', 'хвастаться, демонстрировать'],
    ['a will', 'a legal paper saying who gets your property after you die', 'завещание'],
    ['donate', 'to give something to help others', 'пожертвовать']
  ]},
  { id: 'v3_32a', title: 'p.32 ex.1 · How things go wrong', words: [
    ['be cracked', 'to have a line where something has begun to break', 'быть треснувшим'],
    ['have a piece missing', 'one part is not there', 'не хватает детали'],
    ['a mark', 'a dirty spot on a surface', 'пятно, след'],
    ['give sb spots', 'to cause small red marks on skin', 'вызвать прыщи'],
    ['have a leak', 'to let liquid or gas escape', 'протекать'],
    ['come off', 'to separate from something', 'отвалиться, оторваться'],
    ['fall apart', 'to break into pieces', 'развалиться'],
    ['be ripped', 'to be torn', 'быть порванным'],
    ['be faulty', 'to not work properly', 'быть неисправным'],
    ['be scratched', 'to have thin lines on the surface', 'быть поцарапанным']
  ]},
  { id: 'v3_32b', title: 'p.32 ex.7 · Customer care', words: [
    ['complain', 'to say that you are not satisfied', 'жаловаться'],
    ['compensation', 'money or a gift given for a problem', 'компенсация'],
    ['fail to', 'to not do what is expected', 'не суметь, не сделать'],
    ['be at fault', 'to be responsible for a mistake', 'быть виноватым'],
    ['retain customers', 'to keep customers rather than lose them', 'удерживать клиентов'],
    ['word-of-mouth', 'information passed between people by talking', 'сарафанное радио'],
    ['make an effort', 'to try hard to do something', 'приложить усилия'],
    ['invest in', 'to spend money or time to get a future benefit', 'вкладывать в'],
    ['customer care', 'the service a company gives its customers', 'работа с клиентами']
  ]},
  { id: 'v3_202', title: 'p.202–203 track · Lessons 3A, 3C', words: [
    ['an insole', 'the inside bottom part of a shoe', 'стелька'],
    ['put off', 'to delay doing something', 'откладывать'],
    ['sort sth out', 'to solve a problem', 'уладить, разобраться'],
    ['a stain', 'a dirty mark that is hard to remove', 'пятно'],
    ['rub sth into', 'to press with a circular movement', 'втирать'],
    ['CCTV cameras', 'cameras used for security', 'камеры видеонаблюдения'],
    ['dissatisfied', 'not happy with something', 'недовольный'],
    ['feedback', 'opinions about how good something is', 'обратная связь'],
    ['a valid claim', 'a reasonable demand that is accepted', 'обоснованная претензия'],
    ['deliberately', 'on purpose', 'намеренно'],
    ['awkward', 'difficult to deal with', 'неудобный, сложный'],
    ['policy', 'an official rule of a company', 'правило, политика компании']
  ]},
  { id: 'v3_sh', title: 'Moodle · I can talk about shopping habits', words: [
    ['impulse', 'a sudden desire to do sth without thinking', 'порыв, импульс'],
    ['in search of sth', 'looking for sth', 'в поисках чего-либо'],
    ['price tag', 'a label showing how much you must pay', 'ценник'],
    ['shop till you drop', 'to shop for a very long time', 'ходить по магазинам до изнеможения'],
    ['browse', 'to look casually at things in a shop', 'просматривать, разглядывать'],
    ['after sth', 'looking for and trying to obtain sth', 'в поисках, ради'],
    ['the minute', 'as soon as', 'как только'],
    ['be off', 'to go; to leave', 'уйти, отправиться'],
    ['have an eye for sth', 'to have a natural ability to find sth', 'иметь глаз на что-либо'],
    ['shop around', 'to go to different shops until you find what you want', 'ходить по разным магазинам'],
    ['focused', 'having a very clear aim', 'сосредоточенный'],
    ['be distracted by sth', 'to be unable to pay attention because of sth else', 'отвлекаться на'],
    ['pursuit', 'a hobby or leisure activity', 'занятие, увлечение'],
    ['spree', 'a short period of uncontrolled activity', 'загул, разгул'],
    ['bargain hunting', 'looking for sth at a good, cheap price', 'охота за скидками'],
    ['head for', 'to go in the direction of', 'направляться к'],
    ['indulge in sth', 'to do sth you like, especially sth bad for you', 'потакать своим слабостям, предаваться'],
    ['gadget', 'a small useful piece of equipment', 'гаджет, приспособление'],
    ['shopaholic', 'a person who enjoys shopping too much', 'шопоголик'],
    ['compulsive', 'finding it hard to control your actions', 'навязчивый, патологический'],
    ['addicted to sth', 'unable to stop doing sth harmful', 'зависимый от'],
    ['crippling', 'very serious (debts)', 'неподъёмный, разрушительный'],
    ['outspend', 'to spend more than someone else', 'тратить больше, чем'],
    ['outlive', 'to live longer than someone', 'пережить'],
    ['outnumber', 'to be more in number than', 'превосходить числом'],
    ['outweigh', 'to be greater than', 'перевешивать']
  ]},
  { id: 'v3_ca', title: 'Moodle · Consumer addiction', words: [
    ['consumer addiction', 'a need to buy things just for the sake of buying', 'зависимость от потребления'],
    ['manifest itself', 'to show itself clearly', 'проявляться'],
    ['on-trend', 'fashionable at the moment', 'модный, в тренде'],
    ['upgrade', 'a newer, better version of a product', 'обновление, апгрейд'],
    ['a void', 'an empty space or feeling of missing something', 'пустота'],
    ['unfulfilled', 'not satisfied with what you have achieved', 'неудовлетворённый'],
    ['saturate', 'to fill completely', 'насыщать, переполнять'],
    ['overwhelming', 'very strong; too much to deal with', 'непреодолимый, подавляющий'],
    ['exposed to', 'in contact with something', 'подверженный воздействию'],
    ['make up for', 'to replace something that is missing', 'компенсировать'],
    ['characterized by', 'having a typical feature', 'характеризующийся'],
    ['over-simplistic', 'making something seem simpler than it is', 'слишком упрощённый']
  ]}

];
